config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: "users/registrations"
  }

  resources :users, only: :show do
    resources :contacts, only: :show
    resources :user_files, only: %i[new create show]
  end

  root "pages#home"
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/contact.rb
# frozen_string_literal: true

class Contact < ApplicationRecord
  belongs_to :user
  belongs_to :user_file

  validates :name, presence: true
  validates :name, format: { with: /\A[a-zA-Z0-9\-]+\z/, message: "must be alphanumeric or with '-'" }
  validates :date_of_birth, presence: true
  validates :phone, presence: true
  validates :phone, format: {
    with: /\A\(\+\d{2}\)\s\d{3}[\- ]\d{3}[\- ]\d{2}[\- ]\d{2}\z/,
    message: "format must be (+00) 000 000 00 00 or (+00) 000-000-00-00"
  }
  validates :address, presence: true
  validates :credit_card, presence: true
  validates :email, presence: true
  validates :email, uniqueness: { scope: :user_id }
  validates :email, format: { with: URI::MailTo::EMAIL_REGEXP }
  validates :user_id, presence: true
  validates :user_file_id, presence: true

  validate :date_format
  validate :card_validation

  before_create :set_franchise
  before_create :encrypt_credit_card

  def card_numbers
    ("*" * 10) + Encryption::EncryptionService.decrypt(credit_card)[-4..]
  end

  private

  def date_format
    return true if ymd_format(date_of_birth.to_s)

    add_phone_error
  end

  def ymd_format(date)
    begin
      ymd_format = Date.strptime(date, "%Y-%m-%d").instance_of?(Date)
    rescue TypeError, ArgumentError, Error
      return false
    end

    ymd_format
  end

  def detector
    CreditCardValidations::Detector.new(credit_card)
  end

  def card_validation
    return add_card_error unless detector.valid_luhn?

    true
  end

  def add_phone_error
    errors.add(:date_of_birth, "format must be 'Y-M-D' or 'Y/M/D.")
  end

  def add_card_error
    errors.add(:credit_card, "please enter a valid card number.")
  end

  def set_franchise
    self.franchise = detector.brand.to_s
  end

  def encrypt_credit_card
    self.credit_card = Encryption::EncryptionService.encrypt(credit_card)
  end
end

app/models/rejected_contact.rb
# frozen_string_literal: true

class RejectedContact < ApplicationRecord
  belongs_to :user
  belongs_to :user_file

  validates :user_id, presence: true
  validates :user_file_id, presence: true
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :contacts
  has_many :user_files

  validates :email, presence: true, format: { with: URI::MailTo::EMAIL_REGEXP }
  validates :username, presence: true
  validates :username, uniqueness: true
  validates :username, format: { with: /\A[a-zA-Z0-9]+\z/, message: "must be alphanumeric" }
end

app/models/user_file.rb
# frozen_string_literal: true

class UserFile < ApplicationRecord
  include AASM

  belongs_to :user
  has_many :contacts
  has_many :rejected_contacts

  has_one_attached :csv_file

  attr_reader :contact_name, :email, :phone, :address, :date_of_birth, :credit_card, :franchise

  validates :user_id, presence: true

  aasm do
    state :on_hold, initial: true
    state :processing
    state :terminated

    event :process do
      transitions from: :on_hold, to: :processing
    end

    event :finish do
      transitions from: :processing, to: :terminated
    end
  end

  def download_url
    presigner = Aws::S3::Presigner.new
    presigner.presigned_url(
      :get_object,
      bucket: Rails.application.credentials.aws[:bucket],
      key: name,
      expires_in: 7.days.to_i,
      response_content_disposition: "attachment; filename=\"#{name.split('/').last}\""
    ).to_s
  end
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/contacts_controller.rb
# frozen_string_literal: true

class ContactsController < ApplicationController
  def show
    @contact = Contact.find(params[:id])
  end

  def upload; end
end

app/controllers/pages_controller.rb
# frozen_string_literal: true

class PagesController < ApplicationController
  skip_before_action :authenticate_user!

  def home; end
end

app/controllers/user_files_controller.rb
# frozen_string_literal: true

# rubocop:disable Metrics/AbcSize

class UserFilesController < ApplicationController
  def new
    @user_file = UserFile.new
    @columns = [
      ["Column 1", 0],
      ["Column 2", 1],
      ["Column 3", 2],
      ["Column 4", 3],
      ["Column 5", 4],
      ["Column 6", 5],
      ["Column 7", 6]
    ]
  end

  def create
    aws = aws_object(params[:user_file][:file])
    @user_file = UserFile.new(url: aws.public_url, name: aws.key, user: current_user)

    if @user_file.save
      @user_file.process!
      FilesUploaderJob.perform_later(file_params[:columns], parse_csv(file_params[:file]),
                                     current_user.id, @user_file)
      redirect_to user_path(current_user), success: "File successfully uploaded"
    else
      flash.now[:notice] = "There was an error"
      render :new
    end
  end

  def show
    @file = UserFile.includes(:contacts, :rejected_contacts).find(params[:id])
    @contacts = @file.contacts
    @rejected_contacts = @file.rejected_contacts
  end

  private

  def aws_object(file)
    Aws::AwsService.new.upload(file)
  end

  def parse_csv(file)
    require "csv"

    CSV.open(file, headers: :first_row).map(&:to_h)
  end

  def file_params
    params.require(:user_file).permit(
      :file,
      columns: %i[contact_name email phone address date_of_birth credit_card franchise]
    )
  end
end

# rubocop:enable Metrics/AbcSize

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

module Users
  class RegistrationsController < Devise::RegistrationsController
    before_action :configure_sign_up_params, only: [:create]
    # before_action :configure_account_update_params, only: [:update]

    # GET /resource/sign_up
    # def new
    #   super
    # end

    # POST /resource
    # def create
    #   super
    # end

    # GET /resource/edit
    # def edit
    #   super
    # end

    # PUT /resource
    # def update
    #   super
    # end

    # DELETE /resource
    # def destroy
    #   super
    # end

    # GET /resource/cancel
    # Forces the session data which is usually expired after sign
    # in to be expired now. This is useful if the user wants to
    # cancel oauth signing in/up in the middle of the process,
    # removing all OAuth session data.
    # def cancel
    #   super
    # end

    protected

    # If you have extra params to permit, append them to the sanitizer.
    def configure_sign_up_params
      devise_parameter_sanitizer.permit(:sign_up, keys: %i[username email])
    end
    # If you have extra params to permit, append them to the sanitizer.
    # def configure_account_update_params
    #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
    # end

    # The path used after sign up.
    # def after_sign_up_path_for(resource)
    #   super(resource)
    # end

    # The path used after sign up for inactive accounts.
    # def after_inactive_sign_up_path_for(resource)
    #   super(resource)
    # end
  end
end

app/controllers/users_controller.rb
# frozen_string_literal: true

class UsersController < ApplicationController
  def show
    @user = current_user
    @contacts = @user.contacts
    @files = @user.user_files
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
  def flash_class(type)
    alert_class = {
      "success" => "alert-success",
      "error" => "alert-danger",
      "notice" => "alert-info",
      "alert" => "alert-danger",
      "warn" => "alert-warning"
    }

    alert_class[type]
  end
end

app/helpers/contacts_helper.rb
# frozen_string_literal: true

module ContactsHelper
end

app/helpers/users_helper.rb
# frozen_string_literal: true

module UsersHelper
end

app/views/contacts/_contacts_table.html.erb
<table class="table">
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">Name</th>
      <th scope="col">Date of Birth</th>
      <th scope="col">Phone</th>
      <th scope="col">Address</th>
      <th scope="col">Email</th>
      <th scope="col">Credit Card</th>
      <th scope="col">Franchise</th>
    </tr>
  </thead>
  <tbody>
    <% @contacts.each do|c| %>
      <tr>
        <th scope="row"><%= c.id %></th>
        <td>
          <%= link_to c.name,
                      user_contact_path(user_id: current_user.id, id: c.id),
                      class: "text-decoration-none text-dark" %>
        </td>
        <td><%= c.date_of_birth %></td>
        <td><%= c.phone %></td>
        <td><%= c.address %></td>
        <td><%= c.email %></td>
        <td><%= c.card_numbers %></td>
        <td><%= c.franchise %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/contacts/show.html.erb
<div class="container pt-4 d-flex justify-content-center">
  <div class="card text-center w-50 shadow p-4">
    <div class="card-body">
      <h3 class="card-title"><%= @contact.name %></h3>
    </div>
    <hr>
    <div class="card-body">
      <table class="w-100">
        <thead>
          <th></th>
          <th></th>
        </thead>
        <tbody>
          <tr>
            <td><b>Email:</b></td>
            <td><%= @contact.email %></td>
          </tr>
          <tr>
            <td><b>Phone:</b></td>
            <td><%= @contact.phone %></td>
          </tr>
          <tr>
            <td><b>Address:</b></td>
            <td><%= @contact.address %></td>
          </tr>
          <tr>
            <td><b>Credit Card:</b></td>
            <td><%= @contact.card_numbers %></td>
          </tr>
          <tr>
            <td><b>Franchise:</b></td>
            <td><%= @contact.franchise.capitalize %></td>
          </tr>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ContactImporter</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container-fluid">
      <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <div class="container-fluid">
          <a class="navbar-brand" href="#">Contact Importer</a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
              <% if current_user %>
                <li class="nav-item">
                  <%= link_to "Profile",
                              user_path(id: current_user.id),
                              class: "nav-link active",
                              "aria-current": "page" %>
                </li>
                <li class="nav-item">
                  <%= link_to "Import Contacts", new_user_user_file_path(current_user.id), class: "nav-link" %>
                </li>
              <% end %>
            </ul>
            <div class="session-btns mx-3">
              <%= render partial: "pages/login_logout_btns" %>
            </div>
          </div>
        </div>
      </nav>

      <% flash.each do |type, msg| %>
        <div class="alert <%= flash_class(type) %> alert-dismissible fade show" role="alert">
          <strong><%= msg %></strong>
          <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
        </div>
      <% end %>

      <%= yield %>
    </div>
  </body>
</html>

app/views/pages/_login_logout_btns.html.erb
<% if current_user %>
  <%= link_to "Log Out", destroy_user_session_path, method: :delete, class: "btn btn-danger" %>
<% else %>
  <%= link_to "Sign In", new_user_session_path, class: "btn btn-primary" %>
  <%= link_to "Sign Up", new_user_registration_path, class: "btn btn-primary" %>
<% end %>

app/views/pages/home.html.erb
<div class="d-flex w-100 justify-content-center align-items-center">
  <div class="card mt-5" style="width: 50rem;">
    <div class="card-body text-center d-flex flex-column align-items-center justify-content-center">
      <h5 class="card-title">Contact Importer</h5>
      <p class="card-text w-75">Welcome to contact importer, here you will be able to create/update new contacts by uploading a CSV file.</p>
      <% unless current_user %>
        <p class="card-text">Please Sign In or Sign Up to continue.</p>
        <div class="links">
          <%= render partial: "login_logout_btns" %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/user_files/new.html.erb
<div class="container pt-4 d-flex justify-content-center">
  <div class="card text-center w-50 shadow p-4">
    <div class="card-body">
      <h3 class="card-title">Upload File</h3>
    </div>
    <hr>
    <div class="card-body">
      <%= simple_form_for [current_user, @user_file], input_html: { multipart: true } do |f| %>

        <p>Please select which column belongs to which attribute:</p>

        <div class="form-group d-flex justify-content-between mt-3">
          <%= f.simple_fields_for :columns do |f| %>
            <div>
              <%= f.label :contact_name, "Name" %>
              <%= f.input :contact_name,
                          as: :select,
                          label: false,
                          collection: @columns.map { |c| [c[0], c[1]] },
                          input_html: { class: 'form-control mx-2' },
                          prompt: "-- Select --" %>
            </div>

            <%= f.input :email,
                        as: :select,
                        collection: @columns.map { |c| [c[0], c[1]] },
                        input_html: { class: 'form-control mx-2' },
                        prompt: "-- Select --" %>

            <%= f.input :phone,
                        as: :select,
                        collection: @columns.map { |c| [c[0], c[1]] },
                        input_html: { class: 'form-control mx-2' },
                        prompt: "-- Select --" %>
          </div>

          <div class="form-group d-flex justify-content-between mt-3">
            <%= f.input :address,
                        as: :select,
                        collection: @columns.map { |c| [c[0], c[1]] },
                        input_html: { class: 'form-control mx-2' },
                        prompt: "-- Select --" %>

            <%= f.input :date_of_birth,
                        as: :select,
                        collection: @columns.map { |c| [c[0], c[1]] },
                        input_html: { class: 'form-control mx-2' },
                        prompt: "-- Select --" %>

            <%= f.input :credit_card,
                        as: :select,
                        collection: @columns.map { |c| [c[0], c[1]] },
                        input_html: { class: 'form-control mx-2' },
                        prompt: "-- Select --" %>

            <%= f.input :franchise,
                        as: :select,
                        collection: @columns.map { |c| [c[0], c[1]] },
                        input_html: { class: 'form-control mx-2' },
                        prompt: "-- Select --" %>

          </div>
        <% end %>

        <div class="mt-3">
          <%= f.file_field :file, input_html: { class: 'form-control' } %>
        </div>

        <div class="mt-3">
          <%= f.submit "Upload", class: "btn btn-primary" %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/user_files/show.html.erb
<div class="container pt-4 d-flex justify-content-center">
  <div class="w-75">
    <div class="card text-center shadow p-4">
      <div class="card-body">
        <h3 class="card-title"><%= @file.name.split('/').last %></h3>
      </div>
      <hr>
      <div class="card-body">
        <p>URL: <a href="<%= @file.url %>"><%= @file.name.split('/').last %></a></p>
        <p>Status: <%= @file.aasm_state.capitalize %></a></p>
        <p><%= link_to "Download", @file.download_url %> </p>
      </div>
    </div>

    <div class="card text-center shadow mt-3 p-3">
      <div class="card-body">
        <h3 class="card-title">Imported Contacts</h3>
      </div>
      <hr>
      <%= render partial: "contacts/contacts_table" %>
    </div>

    <div class="card text-center shadow mt-3 p-3">
      <div class="card-body">
        <h3 class="card-title">Rejected Contacts</h3>
      </div>
      <hr>
      <table class="table">
        <thead>
          <tr>
            <th scope="col">#</th>
            <th scope="col">Name</th>
            <th scope="col">Email</th>
            <th scope="col">Reasons</th>
          </tr>
        </thead>
        <tbody>
          <% @rejected_contacts.each do|c| %>
            <tr>
              <th scope="row"><%= c.id %></th>
              <td><%= c.contact_name %></td>
              <td><%= c.contact_email %></td>
              <td><%= c.reasons %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class="container pt-4">
  <div class="row">
    <!-- Profile -->
    <div class="col-4">
      <div class="card">
        <img src="https://via.placeholder.com/700/000000/FFFFFF/?Text=ProfilePic" class="card-img-top" alt="Profile Img">
        <div class="card-body">
          <h5 class="card-title"><%= @user.username %></h5>
          <h6 class="card-title"><%= @user.email %></h6>
          <p class="card-text">Hello, this is your profile.</p>
        </div>
      </div>

      <div class="card my-4">
        <div class="card-body text-center">
          <h5 class="card-title">Imported Files</h5>
          <p>This is the list of your uploaded files:</p>
          <div class="files">
            <ul class="list-group">
              <% @files.each do |file| %>
                <li class="list-group-item">
                  <%= link_to file.name.split('/').last, user_user_file_path(current_user, file) %>
                </li>
              <% end %>
            </ul>
          </div>
        </div>
      </div>
    </div>

    <!-- Contacts -->
    <div class="col">
      <div class="card">
        <div class="card-body text-center">
          <h3 class="card-title">Contacts</h3>
          <p class="card-text">This is the list of contacts you have uploaded via CSV files to your profile.</p>
          <%= render partial: "contacts/contacts_table" %>
        </div>
      </div>
    </div>
  </div>
</div>